services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "ledger"
    volumes:
      - ledger:/var/lib/postgresql/data

volumes:
  ledger:
